# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  save_interval: 2

task:
  _name: audio_pretraining_pseudo_language
  data: ???
  normalize: false
  labels: bpe
  autoregressive: true

dataset:
  num_workers: 6
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 2

distributed_training:
  distributed_world_size: 64
  ddp_backend: legacy_ddp

criterion:
  _name: label_smoothed_cross_entropy
  label_smoothing: 0.1
  # sentence_avg: true
  # zero_infinity: true
  # ctc_weight: 0.5
  report_accuracy: true
  # post_process: sentencepiece

optimization:
  max_update: 400000
  lr: [0.0005]
  sentence_avg: true
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: wav2vec_seq2seq_v2
  w2v_path: ""
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.1
  freeze_finetune_updates: 0
  encoder_embed_dim: 256
  decoder_embed_dim: 256
  decoder_ffn_embed_dim: 1024
  decoder_attention_heads: 4
  decoder_layers: 6
  decoder_layerdrop: 0.05
  decoder_dropout: 0.1
  decoder_attention_dropout: 0.1
  decoder_activation_dropout: 0.0
  share_decoder_input_output_embed: true

  w2v_args:
    task:
      # _name: audio_pretraining
      _name: audio_pretraining_pseudo_language
      data: ???
      max_sample_size: 250000
      min_sample_size: 32000
      normalize: false
      fbank_dim: 0
      mfcc_dim: 0

    model:
      _name: wav2vec2
      quantize_targets: true
      final_dim: 256
      encoder_layerdrop: 0.05
      dropout_input: 0.1
      dropout_features: 0.1
      feature_grad_mult: 0.1
      conv_pos: 128
      encoder_embed_dim: 256
      encoder_attention_heads: 4
      encoder_ffn_embed_dim: 1024
      encoder_layers: 12
      # squeeze_factor: 2
      # squeeze_method: multi-layer
      # conv_feature_layers: '[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512, 2, 2), (512, 2, 2)]'
      # conv_feature_layers: '[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512, 2, 2)] * 2'
      conv_feature_layers: '[(128, 10, 5)] + [(256, 3, 2)] * 2 + [(512, 3, 2)] * 2 + [(1024, 2, 2)] * 2'

      